# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
project_id = "keysely-platform-backend"

[functions.create-connect-account]
verify_jwt = true

[functions.create-marketplace-payment]
verify_jwt = true

[functions.check-connect-status]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.update-space-rating]
verify_jwt = false

[auth.email.smtp]
enabled = true
host = "smtp-relay.brevo.com"
port = 587
user = "98f3ac001@smtp-brevo.com"
pass = "env(BREVO_SMTP_PASS)"
sender_name = "Keysely"
admin_email = "noreply@keysely.com"

